import 'package:flutter/material.dart';

class EzColorScheme extends ColorScheme {
  final String? bgImage;

  const EzColorScheme({
    required super.brightness,
    required super.primary,
    required super.onPrimary,
    super.primaryContainer,
    super.onPrimaryContainer,
    required super.secondary,
    required super.onSecondary,
    super.secondaryContainer,
    super.onSecondaryContainer,
    super.tertiary,
    super.onTertiary,
    super.tertiaryContainer,
    super.onTertiaryContainer,
    required super.error,
    required super.onError,
    super.errorContainer,
    super.onErrorContainer,
    required super.surface,
    required super.onSurface,
    super.surfaceDim,
    super.surfaceBright,
    super.surfaceContainerLowest,
    super.surfaceContainerLow,
    super.surfaceContainer,
    super.surfaceContainerHigh,
    super.surfaceContainerHighest,
    super.onSurfaceVariant,
    super.outline,
    super.outlineVariant,
    super.shadow,
    super.scrim,
    super.inverseSurface,
    super.onInverseSurface,
    super.inversePrimary,
    super.surfaceTint,
    this.bgImage,
  });

  factory EzColorScheme.fromColorScheme(
    ColorScheme colorScheme, {
    String? bgImage,
  }) {
    return EzColorScheme(
      brightness: colorScheme.brightness,
      primary: colorScheme.primary,
      onPrimary: colorScheme.onPrimary,
      primaryContainer: colorScheme.primaryContainer,
      onPrimaryContainer: colorScheme.onPrimaryContainer,
      secondary: colorScheme.secondary,
      onSecondary: colorScheme.onSecondary,
      secondaryContainer: colorScheme.secondaryContainer,
      onSecondaryContainer: colorScheme.onSecondaryContainer,
      tertiary: colorScheme.tertiary,
      onTertiary: colorScheme.onTertiary,
      tertiaryContainer: colorScheme.tertiaryContainer,
      onTertiaryContainer: colorScheme.onTertiaryContainer,
      error: colorScheme.error,
      onError: colorScheme.onError,
      errorContainer: colorScheme.errorContainer,
      onErrorContainer: colorScheme.onErrorContainer,
      surface: colorScheme.surface,
      onSurface: colorScheme.onSurface,
      surfaceDim: colorScheme.surfaceDim,
      surfaceBright: colorScheme.surfaceBright,
      surfaceContainerLowest: colorScheme.surfaceContainerLowest,
      surfaceContainerLow: colorScheme.surfaceContainerLow,
      surfaceContainer: colorScheme.surfaceContainer,
      surfaceContainerHigh: colorScheme.surfaceContainerHigh,
      surfaceContainerHighest: colorScheme.surfaceContainerHighest,
      onSurfaceVariant: colorScheme.onSurfaceVariant,
      outline: colorScheme.outline,
      outlineVariant: colorScheme.outlineVariant,
      shadow: colorScheme.shadow,
      scrim: colorScheme.scrim,
      inverseSurface: colorScheme.inverseSurface,
      onInverseSurface: colorScheme.onInverseSurface,
      inversePrimary: colorScheme.inversePrimary,
      surfaceTint: colorScheme.surfaceTint,
      bgImage: bgImage,
    );
  }

  factory EzColorScheme.fromEzColorScheme(
    EzColorScheme colorScheme, {
    String? bgImage,
  }) {
    return EzColorScheme(
      brightness: colorScheme.brightness,
      primary: colorScheme.primary,
      onPrimary: colorScheme.onPrimary,
      primaryContainer: colorScheme.primaryContainer,
      onPrimaryContainer: colorScheme.onPrimaryContainer,
      secondary: colorScheme.secondary,
      onSecondary: colorScheme.onSecondary,
      secondaryContainer: colorScheme.secondaryContainer,
      onSecondaryContainer: colorScheme.onSecondaryContainer,
      tertiary: colorScheme.tertiary,
      onTertiary: colorScheme.onTertiary,
      tertiaryContainer: colorScheme.tertiaryContainer,
      onTertiaryContainer: colorScheme.onTertiaryContainer,
      error: colorScheme.error,
      onError: colorScheme.onError,
      errorContainer: colorScheme.errorContainer,
      onErrorContainer: colorScheme.onErrorContainer,
      surface: colorScheme.surface,
      onSurface: colorScheme.onSurface,
      surfaceDim: colorScheme.surfaceDim,
      surfaceBright: colorScheme.surfaceBright,
      surfaceContainerLowest: colorScheme.surfaceContainerLowest,
      surfaceContainerLow: colorScheme.surfaceContainerLow,
      surfaceContainer: colorScheme.surfaceContainer,
      surfaceContainerHigh: colorScheme.surfaceContainerHigh,
      surfaceContainerHighest: colorScheme.surfaceContainerHighest,
      onSurfaceVariant: colorScheme.onSurfaceVariant,
      outline: colorScheme.outline,
      outlineVariant: colorScheme.outlineVariant,
      shadow: colorScheme.shadow,
      scrim: colorScheme.scrim,
      inverseSurface: colorScheme.inverseSurface,
      onInverseSurface: colorScheme.onInverseSurface,
      inversePrimary: colorScheme.inversePrimary,
      surfaceTint: colorScheme.surfaceTint,
      bgImage: bgImage,
    );
  }
  
}