part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SETTINGS_UI = _Paths.SETTINGS_UI;
  static const LIST = _Paths.LIST;
  static const GALLERY = _Paths.GALLERY;
  static const CROSS_PLATFORM_SETTINGS = _Paths.CROSS_PLATFORM_SETTINGS;
  static const IOS_DEVELOPER = _Paths.IOS_DEVELOPER;
  static const ANDROID_SETTINGS = _Paths.ANDROID_SETTINGS;
  static const WEB_CHROME_SETTINGS = _Paths.WEB_CHROME_SETTINGS;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const EXAMPLE = _Paths.EXAMPLE;
  static const CHECKMARK_EXAMPLE = _Paths.CHECKMARK_EXAMPLE;
  static const PIN_CODE = _Paths.PIN_CODE;
  static const WELCOME = _Paths.WELCOME;
  static const AUDIO = _Paths.AUDIO;
  static const GRAMMARY = _Paths.GRAMMARY;
  static const BUTTONS = _Paths.BUTTONS;
  static const BUTTON_STYLE = _Paths.BUTTON_STYLE;
  static const MY = _Paths.MY;
  static const INKWELL = _Paths.INKWELL;
  static const GESTURE_OFFICIAL = _Paths.GESTURE_OFFICIAL;
  static const GESTURE_PAN = _Paths.GESTURE_PAN;
  static const GESTURE_DRAG = _Paths.GESTURE_DRAG;
  static const GESTURE_SWIPE = _Paths.GESTURE_SWIPE;
  static const GESTURE_PINCH = _Paths.GESTURE_PINCH;
  static const COLOR_EXAMPLES = _Paths.COLOR_EXAMPLES;
  static const ASYNC_EXAMPLES = _Paths.ASYNC_EXAMPLES;
  static const ROUNDED_PROGRESS_BAR = _Paths.ROUNDED_PROGRESS_BAR;
  static const LIQUID_PROGRESS_BAR = _Paths.LIQUID_PROGRESS_BAR;
  static const STAR_MENU_DEMO = _Paths.STAR_MENU_DEMO;
  static const STAR_MENU_OFFICIAL = _Paths.STAR_MENU_OFFICIAL;
  static const MIX1 = _Paths.MIX1;
  static const M3_SHAPES = _Paths.M3_SHAPES;
  static const HOURGLASS_OFFICIAL = _Paths.HOURGLASS_OFFICIAL;
  static const HOURGLASS_LOADER = _Paths.HOURGLASS_LOADER;
  static const IMAGE_BG = _Paths.IMAGE_BG;
  static const CHECK_THEME = _Paths.CHECK_THEME;
  static const TYPOGRAPHY_COMPARISON = _Paths.TYPOGRAPHY_COMPARISON;
  static const THEME_CHOOSER = _Paths.THEME_CHOOSER;
  static const NOIF = _Paths.NOIF;
  static const REGULAR = _Paths.NOIF + _Paths.REGULAR;
  static const VISIBILITY_EXAMPLE = _Paths.NOIF + _Paths.VISIBILITY_EXAMPLE;
  static const NOVISIBILITY_EXAMPLE = _Paths.NOIF + _Paths.NOVISIBILITY_EXAMPLE;
  static const STATE_MACHINE = _Paths.NOIF + _Paths.STATE_MACHINE;
  static const STATE_MAP = _Paths.NOIF + _Paths.STATE_MAP;
  static const STATE_MACHINE2 = _Paths.NOIF + _Paths.STATE_MACHINE2;
  static const STATE_MACHINE3 = _Paths.NOIF + _Paths.STATE_MACHINE3;
  static const LIQUID_GLASS_MENU = _Paths.LIQUID_GLASS_MENU;
  static const LIQUID_GLASS_EXAMPLE =
      _Paths.LIQUID_GLASS_MENU + _Paths.LIQUID_GLASS_EXAMPLE;
  static const LIQUID_GLASS_SHOWCASE =
      _Paths.LIQUID_GLASS_MENU + _Paths.LIQUID_GLASS_SHOWCASE;
  static const LIQUID_GLASS_PLAYGROUND =
      _Paths.LIQUID_GLASS_MENU + _Paths.LIQUID_GLASS_PLAYGROUND;
  static const REGISTRATION = _Paths.LIQUID_GLASS_MENU + _Paths.REGISTRATION;
  static const SIGNALS = _Paths.SIGNALS;
  static const COUNTER = _Paths.SIGNALS + _Paths.COUNTER;
  static const USER = _Paths.SIGNALS + _Paths.USER;
  static const SCAFFOLD = _Paths.CHECK_THEME + _Paths.SCAFFOLD;
  static const EZSCAFFOLD = _Paths.CHECK_THEME + _Paths.EZSCAFFOLD;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SETTINGS_UI = '/settings-ui';
  static const LIST = '/list';
  static const GALLERY = '/gallery';
  static const CROSS_PLATFORM_SETTINGS = '/cross-platform-settings';
  static const IOS_DEVELOPER = '/ios-developer';
  static const ANDROID_SETTINGS = '/android-settings';
  static const WEB_CHROME_SETTINGS = '/web-chrome-settings';
  static const NOTIFICATIONS = '/notifications';
  static const EXAMPLE = '/example';
  static const CHECKMARK_EXAMPLE = '/checkmark-example';
  static const PIN_CODE = '/pin-code';
  static const WELCOME = '/welcome';
  static const AUDIO = '/audio';
  static const GRAMMARY = '/grammary';
  static const BUTTONS = '/buttons';
  static const BUTTON_STYLE = '/button-style';
  static const MY = '/my';
  static const INKWELL = '/inkwell';
  static const GESTURE_OFFICIAL = '/gesture-official';
  static const GESTURE_PAN = '/gesture-pan';
  static const GESTURE_DRAG = '/gesture-drag';
  static const GESTURE_SWIPE = '/gesture-swipe';
  static const GESTURE_PINCH = '/gesture-pinch';
  static const COLOR_EXAMPLES = '/color-examples';
  static const ASYNC_EXAMPLES = '/async-examples';
  static const ROUNDED_PROGRESS_BAR = '/rounded-progress-bar';
  static const LIQUID_PROGRESS_BAR = '/liquid-progress-bar';
  static const STAR_MENU_DEMO = '/star-menu-demo';
  static const STAR_MENU_OFFICIAL = '/star-menu-official';
  static const MIX1 = '/mix1';
  static const M3_SHAPES = '/m3-shapes';
  static const HOURGLASS_OFFICIAL = '/hourglass-official';
  static const HOURGLASS_LOADER = '/hourglass-loader';
  static const IMAGE_BG = '/image-bg';
  static const CHECK_THEME = '/check-theme';
  static const TYPOGRAPHY_COMPARISON = '/typography-comparison';
  static const THEME_CHOOSER = '/theme-chooser';
  static const VISIBILITY_EXAMPLE = '/visibility-example';
  static const NOVISIBILITY_EXAMPLE = '/novisibility-example';
  static const NOIF = '/noif';
  static const REGULAR = '/regular';
  static const STATE_MACHINE = '/state-machine';
  static const STATE_MAP = '/state-map';
  static const STATE_MACHINE2 = '/state-machine2';
  static const STATE_MACHINE3 = '/state-machine3';
  static const LIQUID_GLASS_MENU = '/liquid-glass-menu';
  static const LIQUID_GLASS_EXAMPLE = '/liquid-glass-example';
  static const LIQUID_GLASS_SHOWCASE = '/liquid-glass-showcase';
  static const LIQUID_GLASS_PLAYGROUND = '/liquid-glass-playground';
  static const REGISTRATION = '/registration';
  static const SIGNALS = '/signals';
  static const COUNTER = '/counter';
  static const USER = '/user';
  static const SCAFFOLD = '/scaffold';
  static const EZSCAFFOLD = '/ezscaffold';
}
